### ISSUE TITLE
Option to hide the context menu

### ISSUE THREAD

**Issue by nassifbasheer** [johncodeos-blog/YouTubeiOSExample#1]
Hi,

Is there an option to hide the context menu in official Youtube library or in WKWebview
![Simulator Screen Shot - iPhone 12 - 2021-11-23 at 09 15 07](https://user-images.githubusercontent.com/5028245/142970409-722b57c6-7a13-40a2-a09b-df6f301e6ff8.png)

**Comment by johncodeos** [comment]
You can find [here](https://developers.google.com/youtube/player_parameters#Parameters) all the parameters the player support.
